services:
  unifi-os-le-cert-deployer:
    image: ghcr.io/mafredri/unifi-os-cert-deployer:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - certificate_state:/data
      - ./secrets:/run/secrets:ro

volumes:
  certificate_state:
